spring.application.name=LibraryManagement
server.port=5070
spring.data.mongodb.uri=mongodb://localhost:27017/library_db

# MongoDB configuration
spring.data.mongodb.database=library_db

# Logging configuration
logging.level.org.dev.lap=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Server configuration
server.servlet.context-path=/

# Enable detailed error messages in development
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false